import { domains, type Domain, type DomainId } from '../data/domains';

export const localeIds = ['en', 'zh-Hant', 'zh-Hans', 'fr'] as const;
export type Locale = (typeof localeIds)[number];
export const localeNames: Record<Locale, string> = { en: 'English', 'zh-Hant': '繁體中文', 'zh-Hans': '简体中文', fr: 'Français' };
const prefixLocales = localeIds.filter((locale): locale is Exclude<Locale, 'en'> => locale !== 'en');

export function isLocale(value: string): value is Locale { return (localeIds as readonly string[]).includes(value); }
export function isPrefixedLocale(value: string): value is Exclude<Locale, 'en'> { return (prefixLocales as readonly string[]).includes(value); }
export function localeFromPath(path: string): Locale {
  const first = path.split('/').filter(Boolean)[0] ?? '';
  return isLocale(first) ? first : 'en';
}
export function unlocalizedPath(path: string): string {
  const segments = path.split('/').filter(Boolean);
  return isPrefixedLocale(segments[0] ?? '') ? `/${segments.slice(1).join('/')}${path.endsWith('/') ? '/' : ''}` || '/' : path;
}
export function localizedPath(path: string, locale: Locale): string {
  const current = localeFromPath(path);
  const segments = path.split('/').filter(Boolean);
  const remainder = segments.slice(1);
  const base = current === 'en' ? path : remainder.length ? `/${remainder.join('/')}${path.endsWith('/') ? '/' : ''}` : '/';
  const normalized = base || '/';
  if (locale === 'en') return normalized;
  return `/${locale}${normalized === '/' ? '/' : normalized.startsWith('/') ? normalized : `/${normalized}`}`;
}
export function localeRoot(locale: Locale): string { return locale === 'en' ? '/' : `/${locale}/`; }

export const copy = {
  en: {
    navLabel: 'Primary navigation', menu: 'Menu', skip: 'Skip to content', connect: 'Let’s connect', language: 'Language', home: 'Johnaverse home',
    domains: { cloud: 'Cloud', ai: 'AI', blockchain: 'Blockchain', cybersecurity: 'Security' } as Record<DomainId, string>,
    homeEyebrow: 'JOHNATHAN L. / SITE RELIABILITY ENGINEER', homeHeadline: 'Reliable systems.', homeAccent: 'Built with intent.', homeIntro: 'I build, secure, and operate infrastructure. From cloud platforms to blockchain networks, I turn complex systems into dependable foundations.', explore: 'Explore my work', github: 'GitHub profile', toronto: 'Toronto, Canada', currentRole: 'Currently at Pinax Network', conceptHome: 'Cloud. Automation. Blockchain. Security.', conceptHomeNote: 'Connected through hands-on engineering.',
    experienceAcross: 'EXPERIENCE ACROSS', domainsEyebrow: 'FOUR DOMAINS / ONE ENGINEERING PRACTICE', domainsHeading: 'Depth where it matters.', domainsIntro: 'Explore each discipline through the systems I work on, the decisions behind them, and the professional experience that shaped my approach.', domainExplore: 'Explore domain',
    working: 'HOW I WORK', workingHeading: 'Understand the system.', workingAccent: 'Make it better.', workingIntro: 'My work sits at the intersection of reliability, automation, and security. I bring production operations and security analysis into the same conversation.', relevantExperience: 'Explore my professional experience',
    practices: [{ title: 'Build with a clear purpose.', body: 'Start with the workload, its constraints, and the people who depend on it. Choose the infrastructure that fits.' }, { title: 'Make the system observable.', body: 'Use monitoring, clear runbooks, and incident investigation to understand how systems behave in practice.' }, { title: 'Automate with boundaries.', body: 'Apply code, deployment workflows, and AI tools thoughtfully, with security and operational control in view.' }],
    foundation: 'THE FOUNDATION', degree: 'BSc (Hons) Information Security', university: 'The Hong Kong Polytechnic University',
    domainSections: 'page sections', overview: 'Overview', capabilities: 'Capabilities', experience: 'Experience', projects: 'Projects', localLab: 'Local lab', allDomains: 'All domains', viewProjects: 'Explore projects', engineeringScope: 'THE ENGINEERING SCOPE', whatWorkOn: 'What I work on.', capabilitiesIntro: 'Practical capabilities, grounded in professional work and the projects below.', backupLink: 'A closer look at backup, recovery & monitoring', experienceEyebrow: 'PROFESSIONAL EXPERIENCE', experienceHeading: 'The work behind the knowledge.', experienceIntro: 'The parts of my career most relevant to', appliedEngineering: 'APPLIED ENGINEERING', projectsHeading: 'Projects & systems.', projectsIntro: 'Public repositories and focused overviews of my work. Explore the purpose, implementation, and contribution behind each project.',
    projectPublic: 'PUBLIC PROJECT', projectOverview: 'PROJECT OVERVIEW', status: { active: 'Active', maintained: 'Maintained', research: 'Research', completed: 'Completed' } as Record<string, string>, projectExplore: 'Explore project', source: 'Source', publicSource: 'View on GitHub', projectDomain: 'DOMAIN', contribution: 'CONTRIBUTION', engineeringContribution: 'Development & engineering', integrationContribution: 'Integration & tooling', genericContribution: 'Contribution', alsoRelevant: 'ALSO RELEVANT TO', evidenceHeading: 'Explore the supporting material', supportingSource: 'Supporting source',
    continueExploring: 'CONTINUE EXPLORING', homeFooter: 'GOOD SYSTEMS START WITH A CONVERSATION', footerHeading: 'Let’s build something', footerAccent: 'that holds up.', motionPause: 'Pause motion', motionResume: 'Resume motion', motionReduced: 'Reduced motion', copyright: '© {year} Johnathan L.',
    localCloud: 'THE LOCAL SIDE OF THE CLOUD', labHeading: 'A lab to build.', labAccent: 'A place to learn.', labIntro: 'Local compute and storage complement cloud services. This is where I explore model serving, infrastructure tooling, and recovery workflows.', labCaption: 'Illustrative hardware composition · model types in my local environment', labTypes: ['AI compute', 'Local workstation', 'Storage & backup'], labLink: 'Explore the infrastructure behind the lab',
    backTo: 'Back to Johnaverse', notFoundTitle: 'A missing connection.', notFoundBody: 'This page has moved or the address is incomplete. Start with the four engineering domains.', notFoundEyebrow: '404 / ROUTE NOT FOUND',
    backupTitle: 'Backup, Recovery & Monitoring', backupDescription: 'Johnathan L.’s approach to backup, recovery, storage, and Grafana monitoring across cloud and local infrastructure.', backupBack: 'Cloud infrastructure', backupEyebrow: 'RESILIENCE / STORAGE & OBSERVABILITY', backupHeadline: 'Recovery is part of the design.', backupLead: 'I treat backups, recovery planning, and monitoring as connected parts of managing infrastructure. A storage system protects data; an observable system helps explain what happened.', backupCards: [{kicker:'01 / BACKUP',title:'Protect the working state.',body:'My local environment includes a Synology DS1618+ for storage and backup work. The 3-2-1 backup strategy is a useful design baseline: keep three copies of important data, on two types of storage, with one copy off-site. Infrastructure definitions and application data need different handling: one describes how to rebuild a system, while the other preserves the state it depends on.'},{kicker:'02 / RECOVERY',title:'Plan the return to service.',body:'My cloud-service work at Hong Kong Telecom included recovery planning and execution. That experience informs how I approach dependencies, restore procedures, and the order in which systems should return.'},{kicker:'03 / MONITORING',title:'Keep the system understandable.',body:'I use Grafana for infrastructure monitoring. My Crypto.com work included L1 blockchain infrastructure monitoring, while my Pinax role includes monitoring and optimizing blockchain operations.'}], backupSummary:'Connecting cloud and local infrastructure', backupSummaryBody:'My current infrastructure work brings together Terraform, container tooling, local storage, and Grafana. The project overviews connect those tools to the systems they support.', backupExplore:'Explore the infrastructure projects',
    detailProject:'Project', imageConcept:'Conceptual illustration', workflowCaption:'Concept / workflow', workflowDescription:'Conceptual project workflow',
  },
  'zh-Hant': {
    navLabel:'主要導覽', menu:'選單', skip:'跳至內容', connect:'聯絡我', language:'語言', home:'Johnaverse 首頁', domains:{cloud:'雲端',ai:'人工智慧',blockchain:'區塊鏈',cybersecurity:'資訊安全'},
    homeEyebrow:'JOHNATHAN L. / 網站可靠性工程師',homeHeadline:'打造可靠系統。',homeAccent:'用心設計，踏實實踐。',homeIntro:'我建置、保護並維運基礎設施。從雲端平台到區塊鏈網路，我將複雜系統化為可靠的根基。',explore:'探索我的作品',github:'GitHub 個人檔案',toronto:'加拿大多倫多',currentRole:'目前任職於 Pinax Network',conceptHome:'雲端、自動化、區塊鏈與安全',conceptHomeNote:'串連實務經驗與工程實踐。',experienceAcross:'曾任職於',domainsEyebrow:'四大領域 / 一套工程實踐',domainsHeading:'深耕領域，回歸實務。',domainsIntro:'透過我參與的系統、設計取捨，以及塑造我工程方法的職涯經驗，認識各項專業。',domainExplore:'探索領域',
    working:'工作方式',workingHeading:'了解系統。',workingAccent:'讓系統更好。',workingIntro:'我的工作結合可靠性、自動化與安全。我會同時考量生產環境維運與安全分析。',relevantExperience:'查看相關職涯經驗',practices:[{title:'明確定義目標。',body:'先了解工作負載、限制，以及仰賴這項服務的人，再選擇合適的基礎設施。'},{title:'讓系統狀況清晰可見。',body:'運用監控、清楚的操作手冊與事件調查，理解系統在實務中的運作情形。'},{title:'為自動化設下界線。',body:'審慎運用程式碼、部署流程與 AI 工具，並兼顧安全與維運管控。'}],foundation:'學歷背景',degree:'資訊安全理學士（榮譽）',university:'香港理工大學',
    domainSections:'本頁導覽',overview:'概覽',capabilities:'專業能力',experience:'職涯經驗',projects:'專案',localLab:'本地實驗室',allDomains:'所有領域',viewProjects:'查看專案',engineeringScope:'工程實務範疇',whatWorkOn:'我的工作內容。',capabilitiesIntro:'以下實務能力均來自專業工作與實際專案。',backupLink:'深入了解備份、復原與監控',experienceEyebrow:'專業職涯',experienceHeading:'職涯累積成就專業。',experienceIntro:'我職涯中與此領域相關的經驗，涵蓋基礎設施維運與軟體工程。',appliedEngineering:'實務工程',projectsHeading:'專案與系統。',projectsIntro:'公開程式碼庫與精選專案說明，介紹每個專案的目的、實作方式與我的貢獻。',
    projectPublic:'公開專案',projectOverview:'專案說明',status:{active:'進行中',maintained:'持續維護',research:'研究中',completed:'已完成'},projectExplore:'查看專案',source:'原始碼',publicSource:'在 GitHub 查看',projectDomain:'領域',contribution:'我的貢獻',engineeringContribution:'開發與工程',integrationContribution:'整合與工具建置',genericContribution:'專案貢獻',alsoRelevant:'相關領域',evidenceHeading:'參考資料',supportingSource:'佐證資料',
    continueExploring:'繼續探索',homeFooter:'好的系統，始於交流',footerHeading:'打造值得信賴的系統',footerAccent:'從一次交流開始。',motionPause:'暫停動畫',motionResume:'恢復動畫',motionReduced:'已減少動態效果',copyright:'© {year} Johnathan L.',localCloud:'雲端的本地實踐',labHeading:'建置實驗環境。',labAccent:'持續學習。',labIntro:'本地運算與儲存設備可補足雲端服務。我會在此測試模型服務、基礎設施工具及復原流程。',labCaption:'硬體示意圖 · 本地環境中的設備類型',labTypes:['AI 運算','本地工作站','儲存與備份'],labLink:'探索實驗環境中的基礎設施',
    backTo:'返回 Johnaverse',notFoundTitle:'找不到連線。',notFoundBody:'頁面可能已移動，或網址不完整。請從四個工程領域開始探索。',notFoundEyebrow:'404 / 找不到頁面',backupTitle:'備份、復原與監控',backupDescription:'Johnathan L. 在雲端與本地基礎設施中的備份、復原、儲存與 Grafana 監控實務。',backupBack:'雲端基礎設施',backupEyebrow:'韌性 / 儲存與可觀測性',backupHeadline:'復原能力也是設計的一環。',backupLead:'我將備份、復原規劃與監控視為管理基礎設施不可分割的一環。儲存系統保護資料，可觀測性則協助釐清發生的狀況。',backupCards:[{kicker:'01 / 備份',title:'保護運作資料。',body:'我的本地環境使用 Synology DS1618+ 處理儲存與備份。3-2-1 備份原則是實用的設計基準：重要資料保留三份副本，存放在兩種不同的儲存媒介，其中一份置於異地。基礎設施定義與應用程式資料需要不同的管理方式：前者說明如何重建系統，後者則保存系統所依賴的狀態。'},{kicker:'02 / 復原',title:'規劃服務恢復。',body:'我在香港電訊的雲端服務工作包含復原規劃與執行。這段經驗影響我對相依性、還原程序及系統恢復順序的思考。'},{kicker:'03 / 監控',title:'讓系統狀況容易理解。',body:'我使用 Grafana 監控基礎設施。在 Crypto.com，我參與 L1 區塊鏈基礎設施監控；在 Pinax，則負責監控與改善區塊鏈維運。'}],backupSummary:'串連雲端與本地基礎設施',backupSummaryBody:'目前的基礎設施工作結合 Terraform、容器工具、本地儲存與 Grafana。各專案說明介紹這些工具所支援的系統。',backupExplore:'查看基礎設施專案',detailProject:'專案',imageConcept:'概念示意圖',workflowCaption:'概念 / 工作流程',workflowDescription:'專案工作流程概念示意圖',
  },
  'zh-Hans': {
    navLabel:'主要导航',menu:'菜单',skip:'跳至正文',connect:'联系我',language:'语言',home:'Johnaverse 首页',domains:{cloud:'云基础设施',ai:'人工智能',blockchain:'区块链',cybersecurity:'网络安全'},
    homeEyebrow:'JOHNATHAN L. / 网站可靠性工程师',homeHeadline:'打造可靠的系统。',homeAccent:'用心设计，扎实落地。',homeIntro:'我负责构建、保护和运维基础设施。从云平台到区块链网络，我将复杂系统变成可靠的根基。',explore:'探索我的作品',github:'GitHub 个人主页',toronto:'加拿大多伦多',currentRole:'目前就职于 Pinax Network',conceptHome:'云基础设施、自动化、区块链与安全',conceptHomeNote:'以实际工程经验串联各个领域。',experienceAcross:'曾就职于',domainsEyebrow:'四大领域 / 一套工程实践',domainsHeading:'深耕领域，回归实战。',domainsIntro:'通过我参与的系统、设计取舍，以及塑造工程方法的职业经验，了解各个专业领域。',domainExplore:'探索领域',
    working:'工作方式',workingHeading:'了解系统。',workingAccent:'让系统变得更好。',workingIntro:'我的工作结合可靠性、自动化与安全。我会同时考虑生产环境运维和安全分析。',relevantExperience:'查看相关职业经历',practices:[{title:'明确目标。',body:'先了解工作负载、限制以及依赖该服务的人，再选择合适的基础设施。'},{title:'让系统运行状态清晰可见。',body:'通过监控、清晰的运行手册和事件调查，了解系统在实际环境中的表现。'},{title:'为自动化设定边界。',body:'审慎使用代码、部署流程和 AI 工具，同时关注安全与运维控制。'}],foundation:'教育背景',degree:'信息安全理学士（荣誉）',university:'香港理工大学',
    domainSections:'本页导航',overview:'概览',capabilities:'专业能力',experience:'职业经历',projects:'项目',localLab:'本地实验室',allDomains:'所有领域',viewProjects:'查看项目',engineeringScope:'工程实践范围',whatWorkOn:'我的工作内容。',capabilitiesIntro:'以下实践能力均来自专业工作和实际项目。',backupLink:'深入了解备份、恢复和监控',experienceEyebrow:'专业经历',experienceHeading:'以职业经历积累专业能力。',experienceIntro:'职业经历中与该领域相关的部分，涵盖基础设施运维和软件工程。',appliedEngineering:'实践工程',projectsHeading:'项目与系统。',projectsIntro:'公开代码库与精简的项目说明，介绍项目的目的、实现方式和我的贡献。',
    projectPublic:'公开项目',projectOverview:'项目说明',status:{active:'进行中',maintained:'持续维护',research:'研究中',completed:'已完成'},projectExplore:'查看项目',source:'源代码',publicSource:'在 GitHub 查看',projectDomain:'领域',contribution:'我的贡献',engineeringContribution:'开发与工程',integrationContribution:'集成与工具开发',genericContribution:'项目贡献',alsoRelevant:'相关领域',evidenceHeading:'参考资料',supportingSource:'佐证资料',
    continueExploring:'继续探索',homeFooter:'好的系统，始于交流',footerHeading:'打造值得信赖的系统',footerAccent:'从一次交流开始。',motionPause:'暂停动画',motionResume:'继续动画',motionReduced:'已减少动态效果',copyright:'© {year} Johnathan L.',localCloud:'云的本地实践',labHeading:'搭建实验环境。',labAccent:'持续学习。',labIntro:'本地计算和存储可以补充云服务。我在这里探索模型服务、基础设施工具和恢复流程。',labCaption:'硬件示意图 · 本地环境中的设备类型',labTypes:['AI 计算','本地工作站','存储与备份'],labLink:'探索实验室中的基础设施',
    backTo:'返回 Johnaverse',notFoundTitle:'找不到连接。',notFoundBody:'此页面可能已移动，或网址不完整。请从四个工程领域开始探索。',notFoundEyebrow:'404 / 找不到页面',backupTitle:'备份、恢复与监控',backupDescription:'Johnathan L. 在云和本地基础设施中的备份、恢复、存储与 Grafana 监控实践。',backupBack:'云基础设施',backupEyebrow:'韧性 / 存储与可观测性',backupHeadline:'恢复能力也是设计的一部分。',backupLead:'我将备份、恢复规划与监控视为基础设施管理中相互关联的环节。存储系统保护数据，可观测性帮助我们了解发生了什么。',backupCards:[{kicker:'01 / 备份',title:'保护当前状态。',body:'我的本地环境使用 Synology DS1618+ 进行存储和备份。3-2-1 备份原则是实用的设计基准：重要数据保留三份副本，存放在两种不同的存储介质，其中一份保存在异地。基础设施定义与应用数据需要不同的处理方式：前者说明如何重建系统，后者保留系统依赖的状态。'},{kicker:'02 / 恢复',title:'规划恢复服务。',body:'我在香港电讯的云服务工作包括恢复规划与执行。这段经历影响了我对依赖关系、恢复步骤以及系统恢复顺序的理解。'},{kicker:'03 / 监控',title:'让系统易于理解。',body:'我使用 Grafana 监控基础设施。在 Crypto.com，我参与 L1 区块链基础设施监控；在 Pinax，我负责监控和优化区块链运维。'}],backupSummary:'连接云和本地基础设施',backupSummaryBody:'我目前的基础设施工作结合了 Terraform、容器工具、本地存储和 Grafana。项目说明介绍这些工具所支持的系统。',backupExplore:'查看基础设施项目',detailProject:'项目',imageConcept:'概念示意图',workflowCaption:'概念 / 工作流',workflowDescription:'项目工作流概念示意图',
  },
  fr: {
    navLabel:'Navigation principale',menu:'Menu',skip:'Aller au contenu',connect:'Me contacter',language:'Langue',home:'Accueil Johnaverse',domains:{cloud:'Cloud',ai:'IA',blockchain:'Blockchain',cybersecurity:'Sécurité'},
    homeEyebrow:'JOHNATHAN L. / INGÉNIEUR FIABILITÉ DES SITES',homeHeadline:'Des systèmes fiables.',homeAccent:'Pensés et construits avec soin.',homeIntro:'Je conçois, sécurise et exploite des infrastructures. Des plateformes cloud aux réseaux blockchain, je transforme des systèmes complexes en bases fiables.',explore:'Voir mes projets',github:'Profil GitHub',toronto:'Toronto, Canada',currentRole:'En poste chez Pinax Network',conceptHome:'Cloud. Automatisation. Blockchain. Sécurité.',conceptHomeNote:'Des domaines réunis par la pratique.',experienceAcross:'EXPÉRIENCES CHEZ',domainsEyebrow:'QUATRE DOMAINES / UNE PRATIQUE D’INGÉNIERIE',domainsHeading:'De l’expertise ancrée dans le réel.',domainsIntro:'Découvrez chaque domaine à travers les systèmes sur lesquels je travaille, mes choix de conception et les expériences qui ont façonné mon approche.',domainExplore:'Explorer le domaine',
    working:'MA MÉTHODE',workingHeading:'Comprendre le système.',workingAccent:'Puis l’améliorer.',workingIntro:'Mon travail associe fiabilité, automatisation et sécurité. Je tiens compte à la fois de l’exploitation en production et de l’analyse de sécurité.',relevantExperience:'Découvrir mon expérience professionnelle',practices:[{title:'Partir d’un objectif clair.',body:'Comprendre la charge, ses contraintes et les personnes qui en dépendent, puis choisir une infrastructure adaptée.'},{title:'Rendre le système observable.',body:'S’appuyer sur la supervision, des procédures claires et l’analyse des incidents pour comprendre son comportement réel.'},{title:'Encadrer l’automatisation.',body:'Utiliser le code, les processus de déploiement et l’IA avec discernement, en gardant la sécurité et le contrôle opérationnel à l’esprit.'}],foundation:'FORMATION',degree:'Licence avec mention en sécurité informatique',university:'The Hong Kong Polytechnic University',
    domainSections:'Sections de cette page',overview:'Présentation',capabilities:'Compétences',experience:'Expérience',projects:'Projets',localLab:'Laboratoire local',allDomains:'Tous les domaines',viewProjects:'Voir les projets',engineeringScope:'PÉRIMÈTRE TECHNIQUE',whatWorkOn:'Mes activités.',capabilitiesIntro:'Des compétences pratiques issues de mon expérience et des projets présentés ici.',backupLink:'En savoir plus sur les sauvegardes, la reprise et la supervision',experienceEyebrow:'EXPÉRIENCE PROFESSIONNELLE',experienceHeading:'La pratique derrière l’expertise.',experienceIntro:'Les expériences de ma carrière les plus pertinentes pour',appliedEngineering:'PROJETS TECHNIQUES',projectsHeading:'Projets et systèmes.',projectsIntro:'Des dépôts publics et des présentations ciblées de mon travail : objectifs, mise en œuvre et contribution.',
    projectPublic:'PROJET PUBLIC',projectOverview:'PRÉSENTATION DU PROJET',status:{active:'En cours',maintained:'Maintenu',research:'Recherche',completed:'Terminé'},projectExplore:'Découvrir le projet',source:'Source',publicSource:'Voir sur GitHub',projectDomain:'DOMAINE',contribution:'CONTRIBUTION',engineeringContribution:'Développement et ingénierie',integrationContribution:'Intégration et outillage',genericContribution:'Contribution',alsoRelevant:'AUSSI LIÉ À',evidenceHeading:'Sources complémentaires',supportingSource:'Source de référence',
    continueExploring:'POURSUIVRE LA VISITE',homeFooter:'LES BONS SYSTÈMES COMMENCENT PAR UN ÉCHANGE',footerHeading:'Construire des systèmes',footerAccent:'sur lesquels compter.',motionPause:'Suspendre les animations',motionResume:'Reprendre les animations',motionReduced:'Animations réduites',copyright:'© {year} Johnathan L.',localCloud:'Le cloud, côté local',labHeading:'Un laboratoire pour construire.',labAccent:'Un espace pour apprendre.',labIntro:'Le calcul et le stockage locaux complètent le cloud. Je m’en sers pour explorer le service de modèles, les outils d’infrastructure et les procédures de reprise.',labCaption:'Illustration du matériel · types de machines utilisés chez moi',labTypes:['Calcul IA','Poste de travail local','Stockage et sauvegarde'],labLink:'Découvrir l’infrastructure de mon laboratoire',
    backTo:'Retour à Johnaverse',notFoundTitle:'Connexion introuvable.',notFoundBody:'Cette page a été déplacée ou l’adresse est incomplète. Commencez par les quatre domaines techniques.',notFoundEyebrow:'404 / PAGE INTROUVABLE',backupTitle:'Sauvegarde, reprise et supervision',backupDescription:'La démarche de Johnathan L. pour la sauvegarde, la reprise, le stockage et la supervision Grafana de ses infrastructures cloud et locales.',backupBack:'Infrastructure cloud',backupEyebrow:'RÉSILIENCE / STOCKAGE ET OBSERVABILITÉ',backupHeadline:'La reprise fait partie de la conception.',backupLead:'Je considère les sauvegardes, la planification de reprise et la supervision comme des éléments liés de l’exploitation d’une infrastructure. Le stockage protège les données ; l’observabilité aide à comprendre les événements.',backupCards:[{kicker:'01 / SAUVEGARDE',title:'Protéger l’état utile.',body:'Mon environnement local comprend un Synology DS1618+ pour le stockage et les sauvegardes. Le principe de sauvegarde 3-2-1 constitue une base utile : conserver trois copies des données importantes, sur deux types de supports, dont une hors site. Les définitions d’infrastructure et les données applicatives ne se gèrent pas de la même façon : les premières décrivent la reconstruction, les secondes préservent l’état nécessaire.'},{kicker:'02 / REPRISE',title:'Planifier le retour au service.',body:'Mon travail sur les services cloud chez Hong Kong Telecom comprenait la planification et l’exécution de reprises. Cette expérience guide mon approche des dépendances, des restaurations et de l’ordre de remise en service.'},{kicker:'03 / SUPERVISION',title:'Garder le système compréhensible.',body:'J’utilise Grafana pour superviser l’infrastructure. Chez Crypto.com, j’ai participé à la supervision d’infrastructures blockchain L1 ; chez Pinax, je contribue à la supervision et à l’optimisation des opérations blockchain.'}],backupSummary:'Relier le cloud à l’infrastructure locale',backupSummaryBody:'Mon travail actuel associe Terraform, les outils de conteneurs, le stockage local et Grafana. Les présentations de projets expliquent les systèmes que ces outils soutiennent.',backupExplore:'Explorer les projets d’infrastructure',detailProject:'Projet',imageConcept:'Illustration conceptuelle',workflowCaption:'Concept / workflow',workflowDescription:'Schéma conceptuel du workflow du projet',
  },
} as const;

export type Messages = (typeof copy)[Locale];
export function messages(locale: Locale): Messages { return copy[locale]; }
export function domainMessage(locale: Locale, id: DomainId): string {
  return locale === 'en' ? domains.find(domain => domain.id === id)!.name : domainCopy[locale][id].name;
}

const domainCopy: Record<Exclude<Locale,'en'>, Record<DomainId, Pick<Domain, 'name'|'shortName'|'headline'|'description'|'intro'|'capabilities'|'diagram'>>> = {
  'zh-Hant': {
    cloud:{name:'雲端與基礎設施',shortName:'雲端',headline:'打造、觀測並復原可靠的基礎設施。',description:'雲端平台、基礎設施即程式碼，以及維持系統穩定運作的日常實踐。',intro:'我的基礎設施經驗涵蓋 Azure Stack 支援、AWS 部署與 Kubernetes 維運。現在我將這些經驗運用於 Terraform、GitOps 與本地運算環境。我重視系統的完整生命週期：如何佈建、如何交付變更、如何發現故障，以及如何復原。',capabilities:[{title:'基礎設施即程式碼',description:'我運用 Terraform 管理雲端資源與容器基礎設施，讓配置易於理解、重現與審慎調整。',tools:['Terraform','OCI','Cloudflare','Docker']},{title:'Kubernetes 與交付',description:'我參與 Kubernetes 遷移與 GitOps 流程，將 Git 中的設定與實際運作的系統連結。',tools:['Kubernetes','FluxCD','GitHub Actions','Helm']},{title:'監控與復原',description:'我將服務健康狀態、日誌與指標連結至實務維運決策，並將備份與復原納入部署考量。',tools:['Grafana','Prometheus','Linux','Synology']},{title:'審慎維運',description:'我依照工作負載需求選擇更新與存取策略，兼顧受控的 fleet 變更與自動容器更新。',tools:['Johnaverse Fleet','Watchtower','Cloudflare Zero Trust','PowerShell']}],diagram:[{title:'定義',subtitle:'以程式碼管理資源與政策'},{title:'交付',subtitle:'可審查的設定變更'},{title:'觀測',subtitle:'健康狀態、日誌與指標'},{title:'復原',subtitle:'備份與維運回應'}]},
    ai:{name:'人工智慧與自動化',shortName:'AI',headline:'讓 AI 工作流程實用，並具備適當管控。',description:'模型基礎設施、代理整合與讓工程師參與其中的開發流程。',intro:'我運用 AI 輔助研究、操作手冊、監控與軟體開發。我關注周邊系統：提供代理適當工具、管控其行為，並檢查結果。工作涵蓋 MCP 介面、模型路由、存取控制，以及我本地環境中的端對端 QA 流程。',capabilities:[{title:'模型與存取',description:'我結合模型路由、基礎設施與存取控制，讓不同工具能使用所需的模型服務。',tools:['LiteLLM','Ollama','Cloudflare Zero Trust']},{title:'工具整合代理',description:'我建置與整合工作流程，將 AI 助理連接到結構化資料、維運知識及明確定義的工具。',tools:['MCP','Hermes','OpenClaw','Codex','Claude']},{title:'維運護欄',description:'我為維運代理開發控制措施，謹慎處理「理解請求」與「對系統採取行動」之間的界線。',tools:['Agent guardrails','Ops UI','Workflow controls']},{title:'開發與 QA',description:'我在程式碼審查及端對端檢查中運用 AI，並將產生的變更視為仍需驗證的工程成果。',tools:['Codex','Claude','Argo Workflows','GitHub Actions','FluxCD','End-to-end QA']}],diagram:[{title:'請求',subtitle:'範圍明確的任務'},{title:'脈絡',subtitle:'知識與結構化工具'},{title:'控管',subtitle:'存取與行動界線'},{title:'審查',subtitle:'檢查行為與結果'}]},
    blockchain:{name:'區塊鏈與資料',shortName:'區塊鏈',headline:'從節點維運到善用鏈上資料。',description:'全節點與歸檔節點、區塊鏈資料服務、網路升級與相關工具。',intro:'在 Pinax，我參與多個網路區塊鏈資料服務背後的基礎設施。經驗涵蓋共識層與執行層用戶端、RPC、Firehose、Substreams 及網路升級。過往也包括智慧合約安全與 Hyperledger Fabric 開發。我亦建置公開工具，讓網路中繼資料與 RPC 工作流程更易於使用。',capabilities:[{title:'節點維運',description:'我參與執行層與共識層用戶端的維運，處理升級、分叉、事件，以及網路變更所需的協調。',tools:['Geth','Nethermind','Besu','Reth','Lighthouse','Prysm','Teku']},{title:'區塊鏈資料管線',description:'我維運透過 RPC 與串流介面提供鏈上資料的服務，包括 The Graph 生態系的 Firehose 與 Substreams。',tools:['RPC','Firehose','Substreams','Token API','The Graph']},{title:'開發者工具',description:'我建置網路註冊資訊與 RPC 工具，串連鏈上中繼資料、端點健康狀態，以及開發者和 AI 助理介面。',tools:['Chains API','Fastify','MCP','Postman','Prometheus']},{title:'合約與部署',description:'我的區塊鏈工作亦涵蓋原始碼與攻擊面分析、企業級帳本開發及 NFT 部署。',tools:['Smart contracts','EVM','Hyperledger Fabric','NFT deployments']}],diagram:[{title:'網路',subtitle:'執行層與共識層用戶端'},{title:'擷取',subtitle:'即時與歷史鏈上資料'},{title:'處理',subtitle:'串流與索引工作流程'},{title:'應用',subtitle:'API、應用程式與工具'}]},
    cybersecurity:{name:'網絡安全',shortName:'安全',headline:'從原始碼到攻擊面進行安全分析。',description:'概念驗證、程式碼分析、威脅情報與安全維運流程。',intro:'我的安全背景涵蓋驗證已回報的漏洞概念驗證、檢視區塊鏈基礎設施及合約，以及建置安全實驗環境。我將原始碼分析與整體系統視角結合，檢視服務、相依元件與信任邊界。現有專案亦將此經驗延伸至威脅情報與 AI 輔助維運控制。',capabilities:[{title:'漏洞與攻擊面分析',description:'我驗證已回報的概念驗證，並檢視驗證者、橋接、鑄造流程與智慧合約的信任邊界。',tools:['Proof-of-concept validation','Smart-contract review','AWS Nitro Enclaves']},{title:'原始碼與執行期測試',description:'我運用靜態分析、動態測試與模糊測試，調查程式行為並支援實際修補。',tools:['SonarScanner','Burp Suite','Go','Rust','Fuzz testing']},{title:'威脅情報與研究',description:'我參與安全中心專案與威脅分析工具開發，串連研究及收集到的訊號，建立更清晰的調查流程。',tools:['CA Security Center','Threat intelligence','Static analysis']},{title:'維運安全',description:'我透過實驗室隔離、維運檢查、存取控制與代理護欄，將安全納入平台工作。',tools:['Linux','OpenShift','Bash','Cloudflare Zero Trust','Agent guardrails']}],diagram:[{title:'了解',subtitle:'程式碼、資產與信任邊界'},{title:'調查',subtitle:'回報、訊號與測試案例'},{title:'驗證',subtitle:'重現並評估行為'},{title:'改善',subtitle:'修補與維運控制'}]},
  },
  'zh-Hans': {
    cloud:{name:'云与基础设施',shortName:'云',headline:'构建、观测并恢复可靠的基础设施。',description:'云平台、基础设施即代码，以及维持系统可靠运行的日常实践。',intro:'我的基础设施经验涵盖 Azure Stack 支持、AWS 部署和 Kubernetes 运维。现在我将这些经验用于 Terraform、GitOps 和本地计算环境。我关注系统的完整生命周期：如何配置、如何交付变更、如何发现故障，以及如何恢复。',capabilities:[{title:'基础设施即代码',description:'我使用 Terraform 管理云资源和容器基础设施，让配置更容易理解、重现和审慎调整。',tools:['Terraform','OCI','Cloudflare','Docker']},{title:'Kubernetes 与交付',description:'我参与 Kubernetes 迁移和 GitOps 流程，将 Git 中的配置与实际运行的系统连接起来。',tools:['Kubernetes','FluxCD','GitHub Actions','Helm']},{title:'监控与恢复',description:'我将服务健康状况、日志和指标关联到实际运维决策，并在部署中考虑备份与恢复。',tools:['Grafana','Prometheus','Linux','Synology']},{title:'有序运维',description:'我根据工作负载需求选择更新和访问策略，兼顾受控的 fleet 变更与自动容器更新。',tools:['Johnaverse Fleet','Watchtower','Cloudflare Zero Trust','PowerShell']}],diagram:[{title:'定义',subtitle:'以代码管理资源与策略'},{title:'交付',subtitle:'可审查的配置变更'},{title:'观测',subtitle:'健康状况、日志与指标'},{title:'恢复',subtitle:'备份与运维响应'}]},
    ai:{name:'人工智能与自动化',shortName:'AI',headline:'让 AI 工作流实用，并实施适当控制。',description:'模型基础设施、代理集成，以及保留工程师参与的开发流程。',intro:'我使用 AI 辅助研究、运行手册、监控和软件开发。我关注外围系统：为代理提供合适的工具，控制其可执行的操作，并检查结果。工作涵盖 MCP 接口、模型路由、访问控制，以及我本地环境中的端到端 QA 流程。',capabilities:[{title:'模型与访问',description:'我结合模型路由、基础设施和访问控制，让不同工具可以使用所需的模型服务。',tools:['LiteLLM','Ollama','Cloudflare Zero Trust']},{title:'工具集成代理',description:'我构建和集成工作流，将 AI 助手连接到结构化数据、运维知识和明确界定的工具。',tools:['MCP','Hermes','OpenClaw','Codex','Claude']},{title:'运维护栏',description:'我为运维代理开发控制措施，谨慎处理“理解请求”和“对系统采取行动”之间的界限。',tools:['Agent guardrails','Ops UI','Workflow controls']},{title:'开发与 QA',description:'我在代码审查和端到端检查中使用 AI，并将生成的变更视为仍需验证的工程工作。',tools:['Codex','Claude','Argo Workflows','GitHub Actions','FluxCD','End-to-end QA']}],diagram:[{title:'请求',subtitle:'范围明确的任务'},{title:'上下文',subtitle:'知识与结构化工具'},{title:'控制',subtitle:'访问与行动边界'},{title:'审查',subtitle:'检查行为与结果'}]},
    blockchain:{name:'区块链与数据',shortName:'区块链',headline:'从运维节点到发挥链上数据的价值。',description:'全节点和归档节点、区块链数据服务、网络升级及相关工具。',intro:'在 Pinax，我参与多个网络区块链数据服务背后的基础设施。经验涵盖共识层和执行层客户端、RPC、Firehose、Substreams 及网络升级。过去的工作还涉及智能合约安全和 Hyperledger Fabric 开发。我也构建公开工具，让网络元数据和 RPC 工作流更易使用。',capabilities:[{title:'节点运维',description:'我参与执行层和共识层客户端运维，处理升级、分叉、事件以及网络变更所需的协调。',tools:['Geth','Nethermind','Besu','Reth','Lighthouse','Prysm','Teku']},{title:'区块链数据管道',description:'我运维通过 RPC 和流式接口提供链上数据的服务，包括 The Graph 生态中的 Firehose 和 Substreams。',tools:['RPC','Firehose','Substreams','Token API','The Graph']},{title:'开发者工具',description:'我构建网络注册信息和 RPC 工具，连接链上元数据、端点健康状况，以及面向开发者和 AI 助手的接口。',tools:['Chains API','Fastify','MCP','Postman','Prometheus']},{title:'合约与部署',description:'我的区块链工作还包括源码和攻击面分析、企业级账本开发及 NFT 部署。',tools:['Smart contracts','EVM','Hyperledger Fabric','NFT deployments']}],diagram:[{title:'网络',subtitle:'执行层与共识层客户端'},{title:'采集',subtitle:'实时与历史链上数据'},{title:'处理',subtitle:'流式和索引工作流'},{title:'应用',subtitle:'API、应用程序与工具'}]},
    cybersecurity:{name:'网络安全',shortName:'安全',headline:'从源代码到攻击面开展安全分析。',description:'概念验证、代码分析、威胁情报和安全运维流程。',intro:'我的安全背景涵盖验证已报告漏洞的概念验证、审查区块链基础设施和合约，以及构建安全实验环境。我将源码分析与整体系统视角结合，检查服务、依赖项和信任边界。当前项目还把这些经验延伸到威胁情报和 AI 辅助运维控制。',capabilities:[{title:'漏洞与攻击面分析',description:'我验证已报告的概念验证，并审查验证者、桥接、铸造流程和智能合约的信任边界。',tools:['Proof-of-concept validation','Smart-contract review','AWS Nitro Enclaves']},{title:'源码与运行时测试',description:'我使用静态分析、动态测试和模糊测试来调查代码行为，支持实际修复。',tools:['SonarScanner','Burp Suite','Go','Rust','Fuzz testing']},{title:'威胁情报与研究',description:'我参与安全中心项目和威胁分析工具开发，将研究与收集到的信号连接起来，形成更清晰的调查流程。',tools:['CA Security Center','Threat intelligence','Static analysis']},{title:'运维安全',description:'我通过实验环境隔离、运维检查、访问控制和代理护栏，将安全纳入平台工作。',tools:['Linux','OpenShift','Bash','Cloudflare Zero Trust','Agent guardrails']}],diagram:[{title:'了解',subtitle:'代码、资产与信任边界'},{title:'调查',subtitle:'报告、信号与测试案例'},{title:'验证',subtitle:'复现并评估行为'},{title:'改进',subtitle:'修复与运维控制'}]},
  },
  fr: {
    cloud:{name:'Cloud et infrastructure',shortName:'Cloud',headline:'Des infrastructures que je peux construire, observer et rétablir.',description:'Plateformes cloud, infrastructure as code et pratiques quotidiennes pour assurer la fiabilité des systèmes.',intro:'Mon expérience de l’infrastructure comprend le support Azure Stack, des déploiements AWS et l’exploitation de Kubernetes. Aujourd’hui, je l’applique à Terraform, à GitOps et à mon environnement informatique local. Je m’intéresse à tout le cycle de vie : provisionner, livrer des changements, détecter les incidents et rétablir le service.',capabilities:[{title:'Infrastructure as code',description:'J’utilise Terraform pour rendre les ressources cloud et l’infrastructure de conteneurs plus faciles à comprendre, reproduire et modifier avec soin.',tools:['Terraform','OCI','Cloudflare','Docker']},{title:'Kubernetes et livraison',description:'Je participe aux migrations Kubernetes et aux workflows GitOps qui relient les configurations dans Git aux systèmes qu’elles pilotent.',tools:['Kubernetes','FluxCD','GitHub Actions','Helm']},{title:'Supervision et reprise',description:'Je relie l’état des services, les journaux et les métriques aux décisions opérationnelles, en tenant compte des sauvegardes et de la reprise.',tools:['Grafana','Prometheus','Linux','Synology']},{title:'Exploitation maîtrisée',description:'J’adapte les stratégies de mise à jour et d’accès à chaque charge, des changements contrôlés de flotte aux mises à jour automatiques de conteneurs.',tools:['Johnaverse Fleet','Watchtower','Cloudflare Zero Trust','PowerShell']}],diagram:[{title:'Définir',subtitle:'Ressources et règles dans le code'},{title:'Livrer',subtitle:'Changements de configuration vérifiables'},{title:'Observer',subtitle:'État, journaux et métriques'},{title:'Rétablir',subtitle:'Sauvegardes et réponse opérationnelle'}]},
    ai:{name:'IA et automatisation',shortName:'IA',headline:'Des workflows IA utiles, avec des garde-fous.',description:'Infrastructure de modèles, intégration d’agents et processus de développement qui gardent l’ingénieur dans la boucle.',intro:'J’utilise l’IA pour la recherche, les procédures, la supervision et le développement logiciel. Je m’intéresse au système autour de l’agent : lui fournir les bons outils, encadrer ses actions et vérifier ses résultats. Cela comprend des interfaces MCP, le routage de modèles, le contrôle des accès et des workflows de QA de bout en bout dans mon environnement.',capabilities:[{title:'Modèles et accès',description:'J’associe le routage des modèles à l’infrastructure et aux contrôles d’accès pour que chaque outil utilise les services dont il a besoin.',tools:['LiteLLM','Ollama','Cloudflare Zero Trust']},{title:'Agents connectés aux outils',description:'Je conçois des workflows qui relient les assistants IA à des données structurées, aux connaissances opérationnelles et à des outils définis.',tools:['MCP','Hermes','OpenClaw','Codex','Claude']},{title:'Garde-fous opérationnels',description:'Je développe des contrôles pour un agent d’exploitation et porte attention à la limite entre interpréter une demande et agir sur un système.',tools:['Agent guardrails','Ops UI','Workflow controls']},{title:'Développement et QA',description:'J’utilise l’IA avec la revue de code et des tests de bout en bout. Les changements générés restent un travail d’ingénierie à vérifier.',tools:['Codex','Claude','Argo Workflows','GitHub Actions','FluxCD','End-to-end QA']}],diagram:[{title:'Demande',subtitle:'Une tâche au périmètre défini'},{title:'Contexte',subtitle:'Connaissances et outils structurés'},{title:'Contrôle',subtitle:'Accès et limites des actions'},{title:'Vérification',subtitle:'Comportement et résultat'}]},
    blockchain:{name:'Blockchain et données',shortName:'Blockchain',headline:'De l’exploitation des nœuds aux usages des données blockchain.',description:'Nœuds complets et d’archive, services de données blockchain, mises à niveau des réseaux et outils associés.',intro:'Chez Pinax, je travaille sur l’infrastructure de services de données blockchain couvrant plusieurs réseaux. Mon expérience comprend les clients de consensus et d’exécution, RPC, Firehose, Substreams et les mises à niveau de réseaux. Mes postes précédents m’ont également apporté une expérience en sécurité des contrats intelligents et en développement Hyperledger Fabric. Je crée aussi des outils publics pour simplifier les métadonnées réseau et les workflows RPC.',capabilities:[{title:'Exploitation des nœuds',description:'Je travaille avec les clients d’exécution et de consensus sur les mises à niveau, les forks, les incidents et leur coordination.',tools:['Geth','Nethermind','Besu','Reth','Lighthouse','Prysm','Teku']},{title:'Pipelines de données blockchain',description:'J’exploite des services qui exposent les données de chaîne par RPC et par streaming, dont Firehose et Substreams pour l’écosystème The Graph.',tools:['RPC','Firehose','Substreams','Token API','The Graph']},{title:'Outils pour développeurs',description:'Je développe des registres réseau et des outils RPC reliant les métadonnées, l’état des points de terminaison et les interfaces pour développeurs et agents IA.',tools:['Chains API','Fastify','MCP','Postman','Prometheus']},{title:'Contrats et déploiements',description:'Mon travail blockchain comprend aussi l’analyse du code et de la surface d’attaque, le développement de registres d’entreprise et des déploiements NFT.',tools:['Smart contracts','EVM','Hyperledger Fabric','NFT deployments']}],diagram:[{title:'Réseau',subtitle:'Clients d’exécution et de consensus'},{title:'Collecte',subtitle:'Données blockchain actuelles et historiques'},{title:'Traitement',subtitle:'Workflows de streaming et d’indexation'},{title:'Usage',subtitle:'API, applications et outils'}]},
    cybersecurity:{name:'Cybersécurité',shortName:'Sécurité',headline:'Analyser la sécurité du code source à la surface d’attaque.',description:'Validation de preuves de concept, analyse de code, renseignement sur les menaces et pratiques opérationnelles sécurisées.',intro:'Mon expérience en sécurité comprend la validation de preuves de concept signalées, l’analyse d’infrastructures blockchain et de contrats, ainsi que la création de laboratoires de sécurité. J’associe l’analyse du code à une vue plus large du système : ses services, ses dépendances et ses limites de confiance. Mes projets actuels étendent ce travail au renseignement sur les menaces et aux contrôles des opérations assistées par l’IA.',capabilities:[{title:'Exploits et surface d’attaque',description:'Je valide les preuves de concept signalées et examine les limites de confiance des validateurs, bridges, flux de minting et contrats intelligents.',tools:['Proof-of-concept validation','Smart-contract review','AWS Nitro Enclaves']},{title:'Tests du code et à l’exécution',description:'Je mène des analyses statiques, des tests dynamiques et du fuzzing pour étudier le comportement du code et faciliter les corrections.',tools:['SonarScanner','Burp Suite','Go','Rust','Fuzz testing']},{title:'Renseignement et recherche',description:'Je contribue à un projet de centre de sécurité et à des outils d’analyse des menaces qui rapprochent la recherche des signaux collectés.',tools:['CA Security Center','Threat intelligence','Static analysis']},{title:'Sécurité opérationnelle',description:'J’intègre la sécurité au travail sur les plateformes grâce à l’isolation des laboratoires, aux contrôles opérationnels, à la gestion des accès et aux garde-fous des agents.',tools:['Linux','OpenShift','Bash','Cloudflare Zero Trust','Agent guardrails']}],diagram:[{title:'Comprendre',subtitle:'Code, actifs et limites de confiance'},{title:'Enquêter',subtitle:'Signalements, alertes et tests'},{title:'Valider',subtitle:'Reproduire et évaluer le comportement'},{title:'Améliorer',subtitle:'Corrections et contrôles opérationnels'}]},
  },
};

export function localizedDomain(domain: Domain, locale: Locale): Domain {
  return locale === 'en' ? domain : { ...domain, ...domainCopy[locale][domain.id] };
}
export function domainPaths(locale: Locale) { return domains.map(domain => ({ params: { domain: domain.id }, props: { domain: localizedDomain(domain, locale) } })); }
