import type { Locale } from './index';

type LocalizedProject = { title: string; summary: string; sections: { heading: string; paragraphs: string[] }[] };
const sectionHeadings = {
  'zh-Hant': ['挑戰', '做法', '我的貢獻與範疇'],
  'zh-Hans': ['挑战', '做法', '我的贡献与范围'],
  fr: ['Le besoin', 'Approche', 'Contribution et périmètre'],
};

const projectCopy: Record<Exclude<Locale,'en'>, Record<string, LocalizedProject>> = {
  'zh-Hant': {
    'chains-api': { title:'Chains API', summary:'區塊鏈網路註冊服務，整合網路中繼資料、端點健康狀態、REST 查詢與 MCP 工具。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['區塊鏈網路資料分散於不同註冊表，網路名稱、鏈識別碼、彼此關係與端點資料也可能互不一致。我希望建立一個共同介面，方便查詢這些資訊，並了解找到的端點。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['Chains API 彙整 The Graph Networks Registry、Chainlist、Chain ID Network 與 SLIP-0044 的資料，為記錄建立索引以供搜尋，保留主網／測試網及 L1／L2 關係，並檢查來源間的不一致。','背景 RPC 檢查補充端點健康資訊。Fastify REST API 提供一般用戶端存取，MCP 工具則將同一份結構化資料提供給 AI 助理。程式庫亦包含可選的工具型助理。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['我將彙整、索引、端點監控與查詢介面整合成可重複使用的服務。開發重點是比對不同來源的記錄、呈現彼此關係，並透過開發者與代理介面提供實用的回應。','公開程式庫包含服務行為與資料驗證測試，GitHub Actions 也執行 lint 與測試。Docker 封裝提供容器化執行方式。']},
    ]},
    'service-log-monitor': { title:'Prometheus 服務復原工具', summary:'一款精簡的 Node.js 工具，用於監看 Linux 服務日誌、依閾值觸發重啟，並提供復原指標。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['服務持續執行時仍可能需要介入。節點維運中的特定日誌錯誤可以成為判斷訊號，但人工反覆查看並不是理想的維運流程。我為此建立一個精簡工具：檢查近期服務日誌，計算指定字串出現次數，達到設定閾值後重啟服務。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['應用程式在 Linux 與 systemd 環境執行。設定值包括服務名稱、日誌範圍、比對字串、觸發閾值與檢查間隔。Node.js 負責協調檢查及呼叫相關系統指令。','Prometheus 指標讓偵測與復原行為可供觀察。工具提供日誌符合事件與服務重啟計數器，便於與其他服務健康訊號一同監控。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['我將偵測、復原與可觀測性連結成小型工具。由維運者明確設定規則、訊號與觸發門檻，可了解工具觀察到什麼以及採取了什麼行動，並繼續調查根本問題。','這是一款專注於服務日誌的工具；公開原始碼與 README 說明其設定及指標。']},
    ]},
    'evm-rpc-postman': { title:'EVM JSON-RPC Postman 集合', summary:'可檢視的 Postman RPC 請求集合，用於探索 EVM 節點介面及除錯流程。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['使用節點時，常從一些簡單問題開始：目前區塊高度為何、交易內容為何，或 RPC 介面提供哪些狀態？可重複使用的請求集合讓這些問題更易探索，也提供可直接檢視的範例。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['我將 EVM JSON-RPC 請求整理為 Postman v2.1 集合。公開檔案包括鏈識別、區塊與交易查詢、餘額、日誌、gas 估算與執行呼叫，也提供除錯、追蹤、網路和用戶端資訊範例。','請求內容皆可直接檢視，開發者可查看方法及參數，配合目標用戶端調整，再比較回應結果。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['我將 RPC 範例整理成可攜式開發工具。這是小型專案，但與節點維運和區塊鏈行為調查相關：能夠直接檢視請求，便更容易理解所用介面。','集合包含多種 RPC 範例及歷史方法。實際支援狀況取決於用戶端、版本與其提供的介面，公開 JSON 檔案是內容的具體參考。']},
    ]},
    'launchpad-charts': { title:'The Graph 部署工具', summary:'引用並標示 GraphOps Helm chart，作為 Firehose 與 graph-node Kubernetes 封裝的公開參考。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['區塊鏈資料服務不只有節點執行檔。Kubernetes 部署封裝還必須描述服務與支援資源，讓工作負載可維運。這連結了我的區塊鏈維運經驗與 Kubernetes、GitOps 工作。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['Launchpad Charts 公開 fork 是 GraphOps 生態工具的參考，其中包含 Firehose Ethereum 與 graph-node 等 Helm charts。Helm 將相關 Kubernetes 資源封裝在一起，方便檢視部署方式及工作負載所需元件。','對 The Graph 資料基礎設施的使用者而言，charts 能將部署封裝與應用程式一同檢視。原始碼亦包含用於檢視索引狀態和查詢效能的 graph-node 儀表板素材。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['Launchpad Charts 由 GraphOps 開發；此專案明確標示上游來源，並以我的公開 fork 作為整合參考。我在此領域的實務經驗包含維運區塊鏈資料服務、Kubernetes 遷移及在 Pinax 使用 FluxCD 交付。','此頁提供可查閱的圖表工具與說明文件，呈現區塊鏈基礎設施、Kubernetes 與維運觀測性的交集。']},
    ]},
    'terraform-cloud-foundation': { title:'Terraform 雲端基礎設施', summary:'以基礎設施即程式碼管理我的 OCI 與 Cloudflare 環境，讓資源與變更在 Git 中清楚可審查。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['運算環境擴大後，手動管理的雲端資源愈來愈難理解與重建。我使用 Terraform 將專案背後的基礎設施寫成程式碼，清楚記錄既有資源及其變更方式。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['這項工作將 OCI 與 Cloudflare 資源納入基礎設施即程式碼流程。OCI 專案說明一組由 Nginx 組成的反向代理設計，使用 Keepalived 管理健康檢查與容錯，也涵蓋憑證更新及兩個代理節點間的同步。','營運方式與佈建工具同樣重要。Git 中的設定可供審查、比較並於需求改變時重新檢視；Cloudflare 網路與存取控制則連接雲端資源和所支援的服務。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['我開發並維護自己的環境 Terraform 設定，延續過往雲端支援與部署經驗，以及目前對 Kubernetes 與 GitOps 的實務認識。','專案說明自動化佈建與後續維運步驟的區別：資源已佈建，並不代表服務已完成驗證。這是持續演進的個人平台工作。']},
    ]},
    'johnaverse-fleet': { title:'Johnaverse Fleet 與 Docker Terraform', summary:'以 Flux GitOps 管理 Kubernetes fleet，並以獨立 Terraform 根模組管理 Docker 服務。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['雲端資源和容器只是整體環境的一部分，執行它們的機器也需要可管理的設定與更新流程。Johnaverse Fleet 和 johnaverse-docker-tf 將這些工作納入我的基礎設施流程。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['Johnaverse Fleet 將 Kubernetes 設定保存在 Git。Flux 從各環境各自的設定路徑進行調和，部分工作負載則透過 image automation 提出映像標籤變更，交由 review branch 審查。','johnaverse-docker-tf 使用彼此獨立的 Terraform root 管理 Docker 服務。共用網路先於其相依服務設定；每個服務都有自己的初始化、驗證與 plan 流程。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['Flux 從 Git 調和 Kubernetes 設定；Docker 服務則透過明確的 Terraform plan 與 apply 流程管理。兩種控制迴路的共同目標，是在變更到達工作負載前，清楚呈現預期狀態及影響範圍。','我維護自己 fleet 與容器環境中的設定、工作負載定義和服務相依性。具狀態 Docker 變更前，流程要求建立可復原備份和回滾路徑，apply 後再驗證服務。更新策略也會依工作負載選擇受控變更或自動容器更新。']},
    ]},
    'model-routing-and-access': { title:'模型路由與受控存取', summary:'使用 LiteLLM 路由模型，並以 Cloudflare Zero Trust 管理工具與 AI 工作流程周邊的存取。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['不同 AI 工具可能依賴不同模型服務。管理這些服務也必須考慮工具如何連線，以及基礎設施周邊的存取邊界。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['我在模型基礎設施中使用 LiteLLM 進行模型路由，並運用 Cloudflare Zero Trust 管理相關存取。這些工作將模型服務連結到環境中的開發、研究與自動化流程。','我將模型層視為平台的一部分，兼顧服務營運方式，以及相依工具如何連線使用。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['這是以現有平台為基礎的整合及基礎設施工作。我將路由與存取元件部署在自己的工作負載周邊，採用其他專案也使用的部署與維運實務。','這項基礎設施支援我持續進行的 AI 實驗與工具。重點是讓周邊系統清楚可控，並能隨工作流程調整。']},
    ]},
    'ops-ui-agent-guardrails': { title:'維運代理安全護欄', summary:'為 Pinax ops-ui 代理自行開發安全控制，界定使用者請求與維運操作之間的邊界。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['連接維運工具的助理需要的不只是合適的答覆，它採取的動作可能影響受管理的系統，因此流程需要控制措施，界定一項請求可轉化為何種行動。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['我為 Pinax 的 ops-ui 代理開發安全護欄，處理 AI 輔助互動與介面背後維運流程之間的界線。','我從安全工程角度檢視哪些動作在範圍內、代理可收到哪些脈絡，以及周邊流程應在哪些位置限制行為。這些控制也是整體工程設計的一部分。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['這是我目前維運工具工作的持續專案，結合區塊鏈基礎設施經驗，以及先前驗證安全行為和檢視攻擊面的工作。','隨著代理和維運流程演進，我持續讓控制邊界清楚易懂。']},
    ]},
    'ai-development-and-qa': { title:'AI 開發與端對端 QA', summary:'在開發流程中整合代理工作流程、程式碼審查與行為檢查型 QA 平台。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['AI 工具可加速開發，但產出的變更仍需符合應用程式需求並如預期運作。我將代理工作流程和審查、端對端 QA 一同使用，讓變更生成仍屬於工程流程的一部分。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['我的環境包括 Hermes、OpenClaw、Codex 與 Claude 工作流程，以及 AI 輔助端對端 QA 平台，支援開發與自動化。','交付設定各司其職：GitHub Actions 執行程式庫檢查，Flux 調和 Kubernetes 設定，Argo Workflows templates 描述可重複的維運任務。明確界定角色，能追蹤變更從來源到執行系統的流程。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['我整合支援自己開發流程的工具與基礎設施，並以安全與維運背景考量產生的程式碼、相依性及其執行系統。不同工具參與不同階段，工程師仍負責審查結果。','這是持續調整中的開發與 QA 環境，我會隨實際專案不斷改善代理與檢查流程的搭配。']},
    ]},
    'ca-security-center': { title:'CA Security Center', summary:'我的安全中心專案之一，亦包括威脅情報與靜態原始碼分析平台工作。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['安全研究可能產生各種待調查資訊：訊號、待檢視原始碼或待驗證的通報。如何整理資訊並支援調查，決定了研究能否轉化為實際工程脈絡。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['CA Security Center 是我目前安全專案的一部分，與威脅情報及靜態原始碼分析平台工作相互補充，讓研究流程更有系統。','我從分析師需要釐清的問題著手：訊號所描述的內容、系統中受影響的位置，以及什麼後續調查能確認其重要性。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['我在自己的環境開發安全工具與流程。過往驗證漏洞回報、分析區塊鏈攻擊面的經驗，影響我如何評估工具呈現的資訊。','專案持續發展；我聚焦於將研究發現整理成有助工程判斷的脈絡，並根據受檢視的系統進行調查。']},
    ]},
    'code-and-contract-analysis': { title:'程式碼與合約安全分析', summary:'以驗證者系統、橋接、鑄造流程與智慧合約經驗為基礎，分析原始碼及攻擊面。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['原始碼中的發現需要脈絡，其重要性取決於元件的用途、輸入及周邊信任邊界。我將程式碼分析與整體系統視角結合。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['我參與靜態原始碼分析平台，以及原始碼、合約與攻擊面分析。這延續我在 Crypto.com 驗證漏洞概念驗證、檢視驗證者基礎設施、鑄造、橋接與智慧合約的經驗。','該職務也包括以 Go 模糊測試調查阻斷服務，對 Go 與 Rust 程式碼進行靜態和動態分析，以及使用 SonarScanner、Burp Suite、維運檢查與監控。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['我將分析師調查流程帶入工具工作：理解程式路徑、檢視系統架構，再評估通報中的行為。我的基礎設施經驗有助於將程式碼層的問題連到實際服務。','目前的專案持續聚焦程式碼分析與安全平台，讓工程師能理解調查結果及相關系統脈絡。']},
    ]},
    'blockchain-data-operations': { title:'區塊鏈資料維運', summary:'全節點與歸檔節點維運、網路變更，以及 The Graph 生態系中的 Firehose 和 Substreams 服務。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['應用程式需要可用的區塊鏈資料，而底層網路持續變化。服務維運涵蓋節點行為、歷史資料、用戶端升級、分叉，以及期間出現的維運事件。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['我參與全節點與歸檔節點，以及以 RPC、Firehose 和 Substreams 為基礎的資料服務。在 Pinax，我維運多網路基礎設施，並使用執行層與共識層用戶端。','網路升級與分叉需要事前準備、協調，亦須在實際行為與預期不符時應變。我的工作也包括 Kubernetes 遷移，以及運用 FluxCD GitOps 交付相關設定。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['我結合節點維運、事件應變，以及與維護網路的社群和團隊協調。公開的服務日誌監控器及 Chains API 亦展現我對復原自動化、端點健康資訊及基礎設施資料易用性的關注。','這是我持續進行的網站可靠性工作；節點維運、網路變更與提供可用資料都是相互關聯的工程責任。']},
    ]},
    'nft-deployment-work': { title:'NFT 部署專案', summary:'結合區塊鏈工程與智慧合約安全背景的 NFT 部署工作。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['我的區塊鏈工作亦包括 NFT 部署專案，與節點基礎設施、企業帳本應用和智慧合約攻擊面分析的經驗並行。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['我會一併考慮合約與周邊應用程式，並以安全背景檢視鑄造流程、權限，以及已部署系統的預期行為。','基礎設施經驗也提供另一個角度：了解區塊鏈應用程式所依賴的節點與資料介面，以及這些介面在開發和維運中的使用方式。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['這些專案將部署工作與我累積的工程與安全經驗結合。實際範圍依專案而異，著重理解部署內容及其預期用途。','NFT 部署補足基礎設施工作的應用程式層，將合約、部署與支援介面置於同一工程脈絡中。']},
    ]},
    'resilience-and-update-policies': { title:'備份、監控與更新策略', summary:'基礎設施的維運層：Grafana 可觀測性、備份，以及依工作負載選擇的更新方式。', sections:[
      {heading:sectionHeadings['zh-Hant'][0],paragraphs:['基礎設施首次部署後仍需持續管理。我將監控、備份與更新視為平台的一部分，與執行應用程式的資源一同規劃。']},
      {heading:sectionHeadings['zh-Hant'][1],paragraphs:['我的環境使用 Grafana 監控及備份基礎設施，並依工作負載明確選擇更新方式。Johnaverse Fleet 支援跨 fleet 受控變更，Watchtower 則為合適的容器工作負載提供自動更新路徑。','策略取決於工作負載；我會考量變更與服務的配合方式、後續可觀測性，以及如何在同一流程中復原。']},
      {heading:sectionHeadings['zh-Hant'][2],paragraphs:['我將此維運層整合並應用於自己的雲端、容器與 AI 專案。過往雲端服務及復原規劃經驗，影響我對持續維護環境的思考。','隨環境演進，這項工作將基礎設施即程式碼的佈建端，連至日常觀測、更新及復原系統的責任。']},
    ]},
  },
  'zh-Hans': {
    'chains-api': {title:'Chains API',summary:'区块链网络注册服务，整合网络元数据、端点健康状况、REST 查询和 MCP 工具。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['区块链网络数据分散在不同注册表中，网络名称、链 ID、关联关系与端点信息也可能不一致。我希望建立一个通用接口，让这些信息更容易查询，并为开发者提供端点背景。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['Chains API 汇总 The Graph Networks Registry、Chainlist、Chain ID Network 和 SLIP-0044 的数据，为记录建立索引以供搜索，并保留主网／测试网及 L1／L2 关系，同时检查来源之间的不一致。','后台 RPC 检查补充端点健康信息。Fastify REST API 服务于常规客户端，MCP 工具则让 AI 助手访问相同的结构化数据。代码库还包含一个可选的工具型助手。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['我把数据聚合、索引、端点监控和查询接口整合为可复用的服务。工程重点包括匹配不同来源的记录、表达它们的关系，并通过面向开发者和代理的接口提供有用响应。','公开代码库包含服务行为和数据验证测试，GitHub Actions 还运行 lint 和测试。Docker 封装提供容器化运行方式。']}]},
    'service-log-monitor': {title:'Prometheus 服务恢复工具',summary:'一款 Node.js 工具，用于监控 Linux 服务日志、按阈值触发重启，并公开恢复指标。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['运行中的服务仍可能进入需要人工干预的状态。节点运维中的特定日志错误可以作为信号，但反复手动查找并不是理想流程。我构建了一个小工具：检查近期服务日志，统计指定短语，达到设置的阈值后重启服务。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['应用运行在 Linux 和 systemd 环境。配置包括服务、日志窗口、匹配短语、阈值和检查间隔。Node.js 协调检查并调用相应系统命令。','Prometheus 指标让检测和恢复活动清晰可见。工具公开日志匹配事件与服务重启计数器，供运维者与其他服务健康信号一同监控。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['我将检测、恢复和可观测性连接成一个精简工具。将规则配置化，可以明确记录运维人员设置的信号及触发操作，让工程师继续调查根本问题。','这是一个专注于服务日志的工具。公开源码和 README 说明了其配置与指标。']}]},
    'evm-rpc-postman': {title:'EVM JSON-RPC Postman 集合',summary:'一组可检查的 Postman RPC 请求，用于探索 EVM 节点接口和调试流程。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['使用节点时常从简单的问题入手：它处理到哪个区块、某笔交易包含什么，或通过 RPC 接口可以看到哪些状态？可复用的请求集合让这些问题更容易探索，也为开发者提供了具体示例。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['我将 EVM JSON-RPC 请求整理在 Postman v2.1 集合中。公开文件包括链身份、区块和交易查询、余额、日志、gas 估算及执行调用，也包含 debug、trace、网络和客户端信息示例。','集合格式让每个请求都可见。开发者可以检查方法和参数、适配目标客户端，并对照响应结果。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['我把 RPC 示例整理成可移植的开发工具。项目规模虽小，却与节点运维和区块链行为调查有关：请求本身可以检查时，使用的接口也更容易理解。','集合涵盖多种 RPC 示例和历史方法。具体支持情况取决于客户端及版本；公开 JSON 文件是内容的直接参考。']}]},
    'launchpad-charts': {title:'The Graph 部署工具',summary:'标明 GraphOps 归属的 Helm chart，作为 Firehose 和 graph-node Kubernetes 部署封装的公开参考。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['区块链数据服务不只是一个节点二进制文件。Kubernetes 部署封装还需要描述服务及其支撑资源，才能让工作负载易于运维。这连接了我的区块链运维经验与 Kubernetes、GitOps 实践。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['Launchpad Charts 公开 fork 展示了该生态中的 GraphOps 工具，其中有 Firehose Ethereum 和 graph-node 等 Helm charts。Helm 将相关 Kubernetes 资源打包在一起，方便检查工作负载如何部署及其需要哪些组件。','对于使用 The Graph 数据基础设施的工程师，这些 charts 提供了应用与部署封装的共同参考。源码还包括用于查看索引状态和查询性能的 graph-node 仪表板素材。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['Launchpad Charts 由 GraphOps 开发。本条目注明上游归属，并将我的公开 fork 作为集成参考。我在这一领域的经验还包括运维区块链数据服务、参与 Kubernetes 迁移，以及在 Pinax 使用 FluxCD 交付。','公开源码展示了可用的部署封装和文档，体现区块链基础设施、Kubernetes 与运维可观测性的结合。']}]},
    'terraform-cloud-foundation': {title:'Terraform 云基础设施',summary:'使用基础设施即代码管理我的 OCI 和 Cloudflare 环境，让资源与变更在 Git 中清晰可审查。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['随着计算环境扩展，手动管理的云资源会变得难以理解和重建。我用 Terraform 将项目背后的基础设施写成代码，记录有哪些资源以及它们如何变化。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['这项工作将 OCI 和 Cloudflare 资源纳入基础设施即代码流程。OCI 项目说明了使用 Nginx 的成对反向代理设计，以 Keepalived 管理健康检查和故障切换，也介绍了证书更新及代理节点之间的同步。','在 Git 中管理配置可以进行审查、比较，并在工作负载需要变化时重新查看。Cloudflare 网络和访问控制则连接云资源与它们所支撑的服务。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['我开发和维护自己环境中的 Terraform 配置，结合过往云服务支持与部署经验，以及当前在 Kubernetes 和 GitOps 方面的工作。','项目文档区分了自动化配置与后续运维步骤：资源已配置完成，并不代表服务已经验证。这是持续演进的个人平台工作。']}]},
    'johnaverse-fleet': {title:'Johnaverse Fleet 与 Docker Terraform',summary:'使用 Flux GitOps 管理 Kubernetes fleet，并通过独立 Terraform root 管理 Docker 服务。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['云资源和容器只是环境的一部分，运行它们的机器也需要便于管理的配置和更新方式。Johnaverse Fleet 与 johnaverse-docker-tf 将这些工作纳入我的基础设施流程。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['Johnaverse Fleet 将 Kubernetes 配置保存在 Git 中。Flux 从各环境自己的配置路径进行协调；一些工作负载使用映像自动化，通过 review branch 提出标签变更供审查。','johnaverse-docker-tf 使用彼此独立的 Terraform root 管理 Docker 服务。共享网络先于依赖它们的服务配置，每项服务都有各自的初始化、验证和 plan 流程。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['Flux 从 Git 协调 Kubernetes 配置；Docker 工作流则使用明确的 Terraform plan 和 apply。两种控制机制都让预期状态和变更范围在应用到工作负载前清晰可见。','我维护自己的 fleet 和容器环境配置、工作负载定义及服务依赖。修改有状态 Docker 服务前，文档要求准备可恢复的备份与回滚方案，并在 apply 后验证服务。更新策略依工作负载决定。']}]},
    'model-routing-and-access': {title:'模型路由与受控访问',summary:'使用 LiteLLM 路由模型，并通过 Cloudflare Zero Trust 管理工具和 AI 工作流周边的访问。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['不同 AI 工具可能依赖不同的模型服务。管理这些服务也需要考虑工具如何连接，以及基础设施周围需要哪些访问边界。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['我在模型基础设施中使用 LiteLLM 进行模型路由，并用 Cloudflare Zero Trust 管理相关访问。该工作连接模型服务与环境中的开发、研究和自动化工作流。','我把模型层当作平台的一部分处理，既关注服务的运维方式，也关注依赖它的工具如何连接。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['这是围绕现有平台开展的集成与基础设施工作。我将路由与访问组件配置到自己的工作负载周边，采用其他项目中相同的部署和运维实践。','这套基础设施为我持续进行的 AI 实验和工具提供支持。我希望随着工作流变化，周边系统仍清晰、可控。']}]},
    'ops-ui-agent-guardrails': {title:'运维代理安全护栏',summary:'为 Pinax ops-ui 代理自主开发安全控制，界定用户请求与运维操作之间的边界。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['连接运维工具的助手需要的不只是恰当的回答。它采取的行动可能影响所管理的系统，因此工作流需要控制措施来界定请求可以转化成什么操作。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['我为 Pinax 的 ops-ui 代理开发安全护栏，处理 AI 辅助交互与界面背后运维流程之间的边界。','我从安全工程角度检查操作范围、代理收到的上下文，以及周边工作流应在哪些位置限制行为。控制措施也是整个系统设计的一部分。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['这是我当前运维工具工作的持续项目，结合了区块链基础设施经验，以及此前验证安全行为和分析攻击面的工作。','随着代理及其运维工作流演进，我持续让控制边界保持清晰易懂。']}]},
    'ai-development-and-qa': {title:'AI 开发与端到端 QA',summary:'将代理工作流、代码审查与行为检查型 QA 平台整合到开发流程中。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['AI 工具可以加快开发，但生成的变更仍需符合应用需求并按预期运行。我把代理工作流与代码审查、端到端 QA 配合使用，让生成变更仍属于工程流程的一部分。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['我的环境包括 Hermes、OpenClaw、Codex 和 Claude 工作流，以及 AI 辅助端到端 QA 平台。','交付配置各有职责：GitHub Actions 运行代码库检查，Flux 协调 Kubernetes 配置，Argo Workflows templates 描述可重复的运维任务。明确各自职责，有助于追踪变更从源代码到执行系统的过程。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['我集成支持自己开发流程的工具与基础设施，并结合安全和运维经验考虑生成的代码、依赖项及运行该代码的系统。不同工具参与不同阶段，工程师仍负责评估结果。','这是持续演进的开发和 QA 环境。我会随着项目推进，调整代理工具和检查流程的配合方式。']}]},
    'ca-security-center': {title:'CA Security Center',summary:'我目前的安全中心项目，同时开展威胁情报与静态源码分析平台相关工作。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['安全研究会产生各种待处理信息：需要调查的信号、待检查的源码，或需要验证的报告。信息如何整理、如何用于调查，决定了研究结果能否形成有用的工程背景。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['CA Security Center 是我当前安全项目工作的一部分，与威胁情报和静态源码分析平台相互配合，让研究流程更有条理。','我从分析师要回答的问题出发：信号说明了什么、它涉及系统的哪一部分，以及后续调查如何确认其意义。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['我在自己的环境中开发安全工具和工作流。此前验证漏洞报告、分析区块链攻击面的经验，影响我对工具提供信息的评估方式。','项目仍在持续发展。我关注如何让研究发现成为有用的工程背景，并依据所分析的系统开展调查。']}]},
    'code-and-contract-analysis': {title:'代码与合约安全分析',summary:'结合验证者系统、桥接、铸造流程和智能合约的实践，分析源码与攻击面。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['代码中的发现需要上下文。它的重要性取决于组件如何使用、接受哪些输入，以及周边有哪些信任边界。我把代码分析与系统整体视角结合起来。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['我参与静态源码分析平台，也开展源码、合约和攻击面分析。这延续了我在 Crypto.com 验证漏洞概念验证，调查验证者基础设施、铸造流程、桥接和智能合约的工作。','该职位还包括用 Go 模糊测试调查拒绝服务问题、对 Go 和 Rust 代码进行静态及动态分析，以及使用 SonarScanner、Burp Suite、运维检查和监控。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['我把分析调查带到工具工作流中：理解代码路径、查看周边架构并评估报告所描述的行为。基础设施经验有助于把代码问题连接到实际运行的服务。','当前项目继续聚焦源码分析与安全平台，帮助工程师基于清晰的系统背景调查和处理发现。']}]},
    'blockchain-data-operations': {title:'区块链数据运维',summary:'全节点和归档节点运维、网络变更，以及 The Graph 生态中的 Firehose 与 Substreams 服务。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['应用需要可用的区块链数据，而底层网络持续变化。服务运维涉及节点行为、历史数据、客户端升级、分叉，以及过程中出现的各类事件。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['我的工作包括全节点、归档节点，以及基于 RPC、Firehose 和 Substreams 的区块链数据服务。在 Pinax，我运维多网络基础设施，并使用执行层和共识层客户端。','网络升级和分叉需要准备与协调；如果实际行为偏离预期，还需要响应。我也参与 Kubernetes 迁移和使用 FluxCD GitOps 交付这些服务的基础设施配置。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['我结合节点运维、事件响应，以及与维护网络的团队和社区协调的工作。公开的服务日志监控工具和 Chains API 项目则体现了我对恢复自动化、端点健康信息与基础设施数据可用性的关注。','这是我持续进行的网站可靠性工作。节点运维、网络变更与可用数据服务都是相关的工程责任。']}]},
    'nft-deployment-work': {title:'NFT 部署项目',summary:'结合区块链工程与智能合约安全经验开展 NFT 部署工作。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['我的区块链工作还包括 NFT 部署项目，与我在节点基础设施、企业账本应用及智能合约攻击面分析方面的经历相辅相成。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['我结合合约及其周边应用考虑部署问题。安全背景使我关注铸造、权限，以及已部署系统的预期行为。','基础设施经验带来另一个视角：了解区块链应用依赖哪些节点和数据接口，以及这些接口在开发和运维中如何使用。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['我把区块链部署工作与职业经历中积累的工程和安全知识结合起来。具体范围因项目而异，重点是理解部署的内容及其用途。','NFT 部署把应用层纳入基础设施工作，让合约、部署及其支撑接口处于同一工程背景中。']}]},
    'resilience-and-update-policies': {title:'备份、监控与更新策略',summary:'环境的运维层：Grafana 可观测性、备份和按工作负载选择的更新策略。',sections:[{heading:sectionHeadings['zh-Hans'][0],paragraphs:['实用的计算环境在首次部署后仍需易于管理。我将监控、备份与更新视为平台的一部分，与运行应用的资源一起考虑。']},{heading:sectionHeadings['zh-Hans'][1],paragraphs:['我的环境结合 Grafana 监控、备份基础设施和明确的更新策略。Johnaverse Fleet 支持跨 fleet 受控变更；Watchtower 为适合的容器工作负载提供自动更新方式。','更新方式取决于工作负载。运维时要考虑变更对服务的影响、之后有哪些可观测信息，以及如何在同一流程中恢复。']},{heading:sectionHeadings['zh-Hans'][2],paragraphs:['我将这套运维机制集成并应用到自己的云、容器和 AI 项目。早期云服务及恢复规划经验影响了我对长期维护环境的理解。','随着环境发展，这项工作将基础设施即代码配置与日常观测、更新和恢复系统的责任联系起来。']}]},
  },
  fr: {
    'chains-api':{title:'Chains API',summary:'Un registre blockchain qui rassemble métadonnées des réseaux, santé des points de terminaison, API REST et outils MCP.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['Les métadonnées blockchain sont réparties entre plusieurs registres. Les noms des réseaux, identifiants de chaîne, relations et points de terminaison peuvent varier selon la source. Je voulais une interface commune pour consulter ces informations et mieux comprendre les points de terminaison trouvés.']},{heading:sectionHeadings.fr[1],paragraphs:['Chains API agrège les données de The Graph Networks Registry, Chainlist, Chain ID Network et SLIP-0044. Le service indexe les enregistrements, conserve les liens mainnet/testnet et L1/L2, puis vérifie les incohérences entre sources.','Des contrôles RPC ajoutent l’état des points de terminaison. L’API REST Fastify sert les clients classiques ; des outils MCP exposent les mêmes données structurées aux assistants IA. Le dépôt comprend aussi un assistant facultatif connecté aux outils.']},{heading:sectionHeadings.fr[2],paragraphs:['J’ai réuni l’agrégation, l’indexation, la supervision des points de terminaison et les interfaces de requête en un service réutilisable. Le travail consiste notamment à rapprocher des enregistrements de sources différentes et à restituer leurs relations.','Le dépôt public teste le comportement du service et la validation ; GitHub Actions lance lint et tests. L’image Docker permet l’exécution en conteneur.']}]},
    'service-log-monitor':{title:'Reprise de service avec Prometheus',summary:'Un outil Node.js qui surveille les journaux Linux, applique un seuil de redémarrage et expose des métriques de reprise.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['Un service qui tourne peut quand même nécessiter une intervention. Dans l’exploitation de nœuds, un message d’erreur précis constitue un signal utile, mais le rechercher manuellement à répétition est peu pratique. J’ai créé un utilitaire qui examine les journaux récents et redémarre le service lorsque le nombre de correspondances atteint un seuil configuré.']},{heading:sectionHeadings.fr[1],paragraphs:['L’application fonctionne sous Linux avec systemd. La configuration définit le service, la fenêtre des journaux, l’expression recherchée, le seuil et l’intervalle de vérification. Node.js coordonne les contrôles et les commandes système correspondantes.','Prometheus rend la détection et la reprise observables. L’outil expose le nombre de correspondances et les redémarrages pour qu’ils soient suivis avec les autres signaux de santé.']},{heading:sectionHeadings.fr[2],paragraphs:['J’ai relié détection, reprise et observabilité dans un outil compact. La règle est configurable : l’opérateur choisit le signal et le nombre de constats nécessaire avant toute action, puis peut enquêter sur le problème sous-jacent.','La source et le README publics expliquent la configuration et les métriques de cet utilitaire ciblé sur les journaux de service.']}]},
    'evm-rpc-postman':{title:'Collection Postman EVM JSON-RPC',summary:'Une collection Postman de requêtes RPC vérifiables pour explorer les interfaces des nœuds EVM et faciliter le débogage.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['L’utilisation d’un nœud commence souvent par une petite question : à quel bloc se trouve-t-il, que contient une transaction ou quelles données son interface RPC expose-t-elle ? Une collection réutilisable facilite ces vérifications avec des exemples concrets.']},{heading:sectionHeadings.fr[1],paragraphs:['J’ai organisé les requêtes EVM JSON-RPC dans une collection Postman v2.1. Le fichier public inclut identité de chaîne, blocs, transactions, soldes, journaux, estimation de gas et appels d’exécution, ainsi que des exemples debug, trace, réseau et informations client.','Chaque requête reste visible et modifiable : le développeur peut inspecter méthode et paramètres, adapter l’exemple au client utilisé, puis comparer la réponse.']},{heading:sectionHeadings.fr[2],paragraphs:['J’ai rassemblé les exemples RPC dans un format portable pour développeurs. Même si le projet est modeste, il complète mon travail d’exploitation des nœuds et d’analyse blockchain : rendre la requête visible aide à comprendre l’interface utilisée.','La collection couvre aussi des méthodes historiques. Leur disponibilité dépend du client, de sa version et des interfaces exposées ; le fichier JSON public décrit précisément son contenu.']}]},
    'launchpad-charts':{title:'Outils de déploiement The Graph',summary:'Une référence aux charts Kubernetes de GraphOps, clairement attribuée, pour Firehose et graph-node.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['Un service de données blockchain ne se limite pas à un binaire de nœud. Le packaging Kubernetes doit aussi décrire les services et ressources nécessaires à son exploitation. Cela relie mon expérience blockchain à Kubernetes et GitOps.']},{heading:sectionHeadings.fr[1],paragraphs:['Mon fork public de Launchpad Charts présente les outils GraphOps de cet écosystème, notamment les charts Firehose Ethereum et graph-node. Helm regroupe les ressources Kubernetes liées pour rendre plus lisible le déploiement d’une charge et de ses composants.','Ces charts permettent d’examiner ensemble le packaging et les services de données The Graph. Le dépôt contient également des tableaux de bord graph-node pour suivre l’indexation et les performances des requêtes.']},{heading:sectionHeadings.fr[2],paragraphs:['Launchpad Charts est développé par GraphOps. Cette présentation attribue le travail amont et décrit mon fork public comme référence d’intégration. Mon expérience inclut aussi l’exploitation de services de données blockchain, la migration Kubernetes et la livraison FluxCD chez Pinax.','Les sources publiques illustrent les charts disponibles et leur documentation, à l’intersection de l’infrastructure blockchain, Kubernetes et de l’observabilité opérationnelle.']}]},
    'terraform-cloud-foundation':{title:'Fondations cloud avec Terraform',summary:'Infrastructure as code pour mon environnement OCI et Cloudflare, afin de documenter et d’examiner les changements dans Git.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['À mesure qu’un environnement grandit, les ressources cloud gérées manuellement deviennent plus difficiles à comprendre et à recréer. J’utilise Terraform pour décrire en code l’infrastructure de mes projets et conserver un historique lisible de ses changements.']},{heading:sectionHeadings.fr[1],paragraphs:['Ce travail rassemble les ressources OCI et Cloudflare dans mon workflow d’infrastructure as code. Mon projet OCI décrit deux reverse proxies Nginx avec contrôles de santé et bascule via Keepalived ; la documentation couvre aussi le renouvellement et la synchronisation des certificats.','Git rend les configurations révisables et comparables. Le réseau et les contrôles d’accès Cloudflare relient les ressources cloud aux services qu’elles soutiennent. Le dépôt distingue le provisionnement automatisé des étapes opérationnelles suivantes : créer une instance ne signifie pas que le service est déjà validé.']},{heading:sectionHeadings.fr[2],paragraphs:['Je développe et maintiens la configuration Terraform de mon propre environnement, en m’appuyant sur mon expérience du support cloud et des déploiements, ainsi que sur mon travail actuel avec Kubernetes et GitOps.','Il s’agit d’une plateforme personnelle en évolution, adaptée aux charges de travail.']}]},
    'johnaverse-fleet':{title:'Johnaverse Fleet et Terraform pour Docker',summary:'Flux GitOps pour ma flotte Kubernetes et racines Terraform indépendantes pour mes services Docker.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['Les ressources cloud et les conteneurs ne représentent qu’une partie d’un environnement. Les machines qui les exécutent ont aussi besoin d’une configuration et de mises à jour gérables. Johnaverse Fleet et johnaverse-docker-tf intègrent ces besoins à mon workflow d’infrastructure.']},{heading:sectionHeadings.fr[1],paragraphs:['Johnaverse Fleet conserve la configuration Kubernetes dans Git. Flux la réconcilie depuis le chemin propre à chaque environnement. Certains workloads utilisent l’automatisation des images pour proposer les mises à jour de tags dans des branches soumises à revue.','johnaverse-docker-tf gère les services Docker avec des racines Terraform indépendantes. Les réseaux partagés sont configurés avant les services qui en dépendent ; chaque service possède son workflow d’initialisation, de validation et de plan.']},{heading:sectionHeadings.fr[2],paragraphs:['Flux réconcilie la configuration Kubernetes depuis Git ; le workflow Docker repose sur des plans et applications Terraform explicites. Ces deux mécanismes rendent l’état visé et la portée d’un changement compréhensibles avant sa mise en production.','Je maintiens les configurations, charges et dépendances de ma flotte et de mon environnement de conteneurs. Les modifications de services Docker avec état prévoient une sauvegarde récupérable et un retour arrière avant application, puis une vérification. La politique de mise à jour dépend du workload.']}]},
    'model-routing-and-access':{title:'Routage des modèles et contrôle des accès',summary:'Routage LiteLLM et accès Cloudflare Zero Trust autour des modèles utilisés par mes outils et workflows IA.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['Les outils IA peuvent dépendre de services de modèles différents. Il faut également savoir comment ils s’y connectent et quelles limites d’accès entourent l’infrastructure.']},{heading:sectionHeadings.fr[1],paragraphs:['J’utilise LiteLLM pour le routage des modèles et Cloudflare Zero Trust dans l’infrastructure d’accès associée. Le travail relie les services de modèles aux workflows de développement, de recherche et d’automatisation de mon environnement.','Je traite la couche modèle comme une composante de plateforme : elle a besoin d’un mode d’exploitation clair et de connexions adaptées pour les outils qui en dépendent.']},{heading:sectionHeadings.fr[2],paragraphs:['Il s’agit d’un travail d’intégration et d’infrastructure autour de plateformes existantes. Je réunis le routage et les contrôles d’accès autour de mes propres charges de travail avec les pratiques que j’utilise dans les autres projets.','L’infrastructure soutient mes outils et expérimentations IA. Mon objectif est qu’elle reste compréhensible et contrôlable à mesure que les workflows évoluent.']}]},
    'ops-ui-agent-guardrails':{title:'Garde-fous pour un agent opérationnel',summary:'Contrôles de sécurité développés pour l’agent ops-ui de Pinax, afin d’encadrer le passage d’une demande à une action opérationnelle.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['Un assistant connecté à des outils opérationnels a besoin de plus qu’une réponse utile : ses actions peuvent affecter le système. Le workflow doit donc définir ce qu’une demande peut autoriser.']},{heading:sectionHeadings.fr[1],paragraphs:['Je développe des garde-fous de sécurité pour l’agent ops-ui de Pinax, à la frontière entre l’interaction assistée par IA et les workflows opérationnels de l’interface.','Mon approche examine les actions autorisées, le contexte transmis à l’agent et les points où le workflow doit limiter son comportement. Ces contrôles sont des décisions d’ingénierie à part entière.']},{heading:sectionHeadings.fr[2],paragraphs:['Ce projet est en cours dans le cadre de mes outils opérationnels. Il associe mon expérience d’infrastructure blockchain à mon travail antérieur de validation de comportements de sécurité et d’analyse des surfaces d’attaque.','Je veille à garder les limites de contrôle compréhensibles à mesure que l’agent et ses workflows évoluent.']}]},
    'ai-development-and-qa':{title:'Développement assisté par l’IA et QA de bout en bout',summary:'Des workflows d’agents, une revue de code et des plateformes de QA comportementale pour soutenir le développement.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['Les outils IA accélèrent le développement, mais les changements doivent toujours convenir à l’application et fonctionner comme prévu. J’associe les workflows d’agents à la revue et aux tests de bout en bout pour garder la génération dans un processus d’ingénierie.']},{heading:sectionHeadings.fr[1],paragraphs:['Mon environnement comprend Hermes, OpenClaw, Codex, Claude et des plateformes IA de QA de bout en bout.','Les outils de livraison ont des rôles distincts : GitHub Actions exécute les contrôles du dépôt, Flux réconcilie les configurations Kubernetes et les templates Argo Workflows décrivent des tâches opérationnelles répétables. Ces responsabilités explicites permettent de suivre une modification jusqu’au système qui l’exécute.']},{heading:sectionHeadings.fr[2],paragraphs:['J’intègre les outils et l’infrastructure qui soutiennent mon workflow. Mon expérience de la sécurité et de l’exploitation m’amène à considérer ensemble le code généré, ses dépendances et le système où il s’exécute. L’ingénieur reste responsable de l’évaluation du résultat.','Cet environnement de développement et de QA évolue à mesure que j’affine la place des agents et des contrôles dans mes projets.']}]},
    'ca-security-center':{title:'CA Security Center',summary:'Mon projet actuel de centre de sécurité, en parallèle de travaux sur le renseignement et l’analyse statique du code.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['La recherche en sécurité produit différents éléments à examiner : un signal, du code source ou un rapport à valider. L’organisation de ces informations et leur utilité pour l’enquête font la différence.']},{heading:sectionHeadings.fr[1],paragraphs:['CA Security Center s’inscrit dans mes projets de sécurité, aux côtés de plateformes de renseignement sur les menaces et d’analyse statique du code.','Je pars des questions d’un analyste : que décrit le signal, quelle partie du système est concernée et quelle enquête permet d’en établir la portée ?']},{heading:sectionHeadings.fr[2],paragraphs:['Je travaille sur les outils et workflows de sécurité de mon propre environnement. Mon expérience de validation de signalements d’exploits et d’analyse de surfaces d’attaque blockchain guide l’évaluation des informations présentées.','Le projet reste actif et évolue avec mes recherches en sécurité. Mon objectif est de relier les résultats aux systèmes examinés pour produire un contexte utile aux ingénieurs.']}]},
    'code-and-contract-analysis':{title:'Analyse de sécurité du code et des contrats',summary:'Analyse du code et des surfaces d’attaque, éclairée par mon expérience des validateurs, bridges, flux de minting et contrats intelligents.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['Un constat dans le code source a besoin de contexte : son importance dépend de l’utilisation du composant, de ses entrées et des limites de confiance qui l’entourent. Mon travail relie l’analyse du code à la vue d’ensemble du système.']},{heading:sectionHeadings.fr[1],paragraphs:['Je travaille sur des plateformes d’analyse statique ainsi que sur l’analyse du code, des contrats et des surfaces d’attaque. Cela s’appuie sur mon expérience chez Crypto.com : validation de preuves de concept signalées et étude des validateurs, du minting, des bridges et des contrats intelligents.','Ce poste comprenait aussi du fuzzing Go pour étudier les dénis de service, l’analyse statique et dynamique de code Go et Rust, et l’utilisation de SonarScanner, Burp Suite, de contrôles opérationnels et de supervision.']},{heading:sectionHeadings.fr[2],paragraphs:['J’intègre à l’outillage la démarche de l’analyste : comprendre le chemin d’exécution, examiner l’architecture et évaluer le comportement signalé. Mon expérience d’infrastructure relie les enjeux du code aux services qui l’exécutent.','Mes projets actuels restent centrés sur l’analyse du code et les plateformes de sécurité, avec suffisamment de contexte pour que les ingénieurs puissent étudier et traiter les constats.']}]},
    'blockchain-data-operations':{title:'Exploitation des données blockchain',summary:'Exploitation de nœuds complets et d’archive, changements de réseau et services Firehose et Substreams dans l’écosystème The Graph.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['Les applications ont besoin de données blockchain utilisables alors que les réseaux évoluent. L’exploitation comprend le comportement des nœuds, l’historique, les mises à niveau des clients, les forks et les incidents associés.']},{heading:sectionHeadings.fr[1],paragraphs:['Mon travail comprend des nœuds complets et d’archive ainsi que des services de données autour de RPC, Firehose et Substreams. Chez Pinax, j’exploite plusieurs réseaux et travaille avec les clients d’exécution et de consensus.','Les mises à niveau et les forks exigent préparation et coordination, puis une réponse si le comportement diffère des attentes. Je participe également à la migration Kubernetes et à la livraison GitOps avec FluxCD de l’infrastructure concernée.']},{heading:sectionHeadings.fr[2],paragraphs:['J’associe exploitation des nœuds, réponse aux incidents et coordination avec les équipes et communautés qui maintiennent les réseaux. Mes projets publics de supervision des journaux et Chains API reflètent le même intérêt pour la reprise, la santé des points de terminaison et l’accès aux informations d’infrastructure.','Ce travail se poursuit dans mon rôle en fiabilité des sites : exploitation des nœuds, changements réseau et données utilisables sont liés.']}]},
    'nft-deployment-work':{title:'Projets de déploiement NFT',summary:'Des projets de déploiement NFT nourris par mon expérience en ingénierie blockchain et en sécurité des contrats intelligents.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['Mon travail blockchain comprend aussi des projets de déploiement NFT, en lien avec mon expérience des nœuds, des registres d’entreprise et de l’analyse des surfaces d’attaque des contrats intelligents.']},{heading:sectionHeadings.fr[1],paragraphs:['J’examine le déploiement dans le contexte du contrat et de l’application qui l’entoure. Mon expérience en sécurité guide mes questions sur le minting, les permissions et le comportement attendu.','Mon expérience de l’infrastructure aide aussi à comprendre les interfaces de nœuds et de données dont dépend l’application, et leur usage lors du développement et de l’exploitation.']},{heading:sectionHeadings.fr[2],paragraphs:['J’aborde le déploiement blockchain avec les compétences techniques et de sécurité développées au fil de mes postes. Le périmètre varie selon le projet, en tenant compte de ce qui est déployé et de son usage prévu.','Le déploiement NFT relie le contrat, sa mise en service et les interfaces qui l’accompagnent dans un même contexte d’ingénierie.']}]},
    'resilience-and-update-policies':{title:'Sauvegardes, supervision et mises à jour',summary:'La couche opérationnelle de mon environnement : visibilité Grafana, sauvegardes et décisions de mise à jour adaptées aux charges.',sections:[{heading:sectionHeadings.fr[0],paragraphs:['Un environnement informatique utile doit rester gérable après son premier déploiement. Je considère supervision, sauvegardes et mises à jour comme des éléments de la plateforme, au même titre que les ressources applicatives.']},{heading:sectionHeadings.fr[1],paragraphs:['Mon environnement associe la supervision Grafana et les sauvegardes à une stratégie explicite de mises à jour. Johnaverse Fleet permet des changements contrôlés de la flotte ; Watchtower offre une voie de mise à jour automatique pour les conteneurs adaptés.','La politique dépend de la charge : il faut tenir compte de l’impact du changement, de la visibilité ensuite et de la manière de rétablir le service.']},{heading:sectionHeadings.fr[2],paragraphs:['J’intègre et exploite ces mécanismes autour de mes propres projets cloud, conteneurs et IA. Mon expérience du support cloud et de la planification de reprise nourrit ma façon de garder un environnement opérationnel.','Ce travail relie le provisionnement par infrastructure as code à la responsabilité continue d’observer, de mettre à jour et de rétablir les systèmes.']}]},
  },
};

export function localizedProject(id: string, locale: Locale): LocalizedProject | undefined {
  return locale === 'en' ? undefined : projectCopy[locale][id];
}

const stageLabels: Record<Exclude<Locale,'en'>, Record<string,string[]>> = {
  'zh-Hant': {
    'chains-api':['資料來源','註冊表','REST / MCP'],'service-log-monitor':['日誌','閾值','重啟','指標'],'evm-rpc-postman':['方法','請求','RPC 節點','回應'],'launchpad-charts':['Helm charts','Kubernetes','服務'],'terraform-cloud-foundation':['Terraform','計畫','OCI','Cloudflare'],'johnaverse-fleet':['Git','Flux','Terraform','Docker'],'model-routing-and-access':['工具','存取','LiteLLM','模型'],'ops-ui-agent-guardrails':['請求','安全護欄','工具操作'],'ai-development-and-qa':['變更','審查','QA','回饋'],'ca-security-center':['訊號','分類','調查'],'code-and-contract-analysis':['原始碼','分析','發現'],'blockchain-data-operations':['節點','RPC','Firehose','Substreams'],'nft-deployment-work':['合約','部署','應用程式'],'resilience-and-update-policies':['服務','備份','Grafana','更新'],
  },
  'zh-Hans': {
    'chains-api':['数据源','注册表','REST / MCP'],'service-log-monitor':['日志','阈值','重启','指标'],'evm-rpc-postman':['方法','请求','RPC 节点','响应'],'launchpad-charts':['Helm charts','Kubernetes','服务'],'terraform-cloud-foundation':['Terraform','计划','OCI','Cloudflare'],'johnaverse-fleet':['Git','Flux','Terraform','Docker'],'model-routing-and-access':['工具','访问','LiteLLM','模型'],'ops-ui-agent-guardrails':['请求','安全护栏','工具操作'],'ai-development-and-qa':['变更','审查','QA','反馈'],'ca-security-center':['信号','分类','调查'],'code-and-contract-analysis':['源码','分析','发现'],'blockchain-data-operations':['节点','RPC','Firehose','Substreams'],'nft-deployment-work':['合约','部署','应用程序'],'resilience-and-update-policies':['服务','备份','Grafana','更新'],
  },
  fr: {
    'chains-api':['Sources','Registre','REST / MCP'],'service-log-monitor':['Journaux','Seuil','Redémarrage','Métriques'],'evm-rpc-postman':['Méthodes','Requête','Nœud RPC','Réponse'],'launchpad-charts':['Charts Helm','Kubernetes','Services'],'terraform-cloud-foundation':['Terraform','Plan','OCI','Cloudflare'],'johnaverse-fleet':['Git','Flux','Terraform','Docker'],'model-routing-and-access':['Outils','Accès','LiteLLM','Modèles'],'ops-ui-agent-guardrails':['Demande','Garde-fous','Action'],'ai-development-and-qa':['Modification','Revue','QA','Retour'],'ca-security-center':['Signaux','Triage','Enquête'],'code-and-contract-analysis':['Code source','Analyse','Constats'],'blockchain-data-operations':['Nœuds','RPC','Firehose','Substreams'],'nft-deployment-work':['Contrat','Déploiement','Application'],'resilience-and-update-policies':['Services','Sauvegardes','Grafana','Mises à jour'],
  },
};

export function localizedWorkflowStages(id: string, locale: Locale): string[] | undefined {
  return locale === 'en' ? undefined : stageLabels[locale][id];
}
